"*":
  push:
    - imports:
      - https://cnb.cool/frigate-cn/github-key/-/blob/87d2daf01d7346e48f6d45986c579f82e28a4d57/github-token.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Frigate-CN/docs.git
            auth_type: https
            username: ${github_username}
            password: ${github_access_token}

main:
  push:
    - stages:
      - name: build knowledge base
        image: docker.cnb.cool/johannli/knowledge-base
        settings:
          include: "docs/**/**.md"