import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { PropSidebarItemLink } from "@docusaurus/plugin-content-docs";
import frigateHttpApiSidebar from "./docs/integrations/api/sidebar";

const sidebars: SidebarsConfig = {
  docs: {
    Frigate: [
      "frigate/index",
      "frigate/hardware",
      "frigate/installation",
      "frigate/camera_setup",
      "frigate/video_pipeline",
      "frigate/glossary",
    ],
    向导: [
      "guides/getting_started",
      "guides/configuring_go2rtc",
      "guides/ha_notifications",
      "guides/ha_network_storage",
      "guides/reverse_proxy",
    ],
    配置: {
      "配置文件": [
        "configuration/index",
        "configuration/reference",
        {
          type: "link",
          label: "Go2RTC 配置参考",
          href: "https://github.com/AlexxIT/go2rtc/tree/v1.9.9#configuration",
        } as PropSidebarItemLink,
      ],
      检测: [
        "configuration/object_detectors",
        "configuration/audio_detectors",
      ],
      识别: [
        "configuration/semantic_search",
        "configuration/genai",
        "configuration/face_recognition",
        "configuration/license_plate_recognition",
        "configuration/bird_classification",
      ],
      摄像头: [
        "configuration/cameras",
        "configuration/review",
        "configuration/record",
        "configuration/snapshots",
        "configuration/motion_detection",
        "configuration/birdseye",
        "configuration/live",
        "configuration/restream",
        "configuration/autotracking",
        "configuration/camera_specific",
      ],
      对象: [
        "configuration/object_filters",
        "configuration/masks",
        "configuration/zones",
        "configuration/objects",
        "configuration/stationary_objects",
      ],
      "硬件加速": [
        "configuration/hardware_acceleration_video",
        "configuration/hardware_acceleration_enrichments",
      ],
      "扩展配置": [
        "configuration/authentication",
        "configuration/notifications",
        "configuration/ffmpeg_presets",
        "configuration/pwa",
        "configuration/tls",
        "configuration/advanced",
      ],
    },
    API接口: [
      "integrations/plus",
      "integrations/home-assistant",
      // This is the HTTP API generated by OpenAPI
      {
        type: "category",
        label: "HTTP API",
        link: {
          type: "generated-index",
          title: "Frigate HTTP API",
          description: "HTTP API",
          slug: "/integrations/api/frigate-http-api",
        },
        items: frigateHttpApiSidebar,
      },
      "integrations/mqtt",
      "configuration/metrics",
      "integrations/third_party_extensions",
    ],
    "Frigate+": [
      "plus/index",
      'plus/annotating',
      "plus/first_model",
      "plus/faq",
    ],
    常见问题: [
      "troubleshooting/faqs",
      "troubleshooting/recordings",
      "troubleshooting/gpu",
      "troubleshooting/edgetpu",
    ],
    开发: [
      "development/contributing",
      "development/contributing-boards",
    ],
  },
};

export default sidebars;
